model.sh a_class_train.arff a_class_train.model
model.sh a_jazz_train.arff a_jazz_train.model
model.sh a_kar_train.arff a_kar_train.model
model.sh b_class_train.arff b_class_train.model
model.sh b_jazz_train.arff b_jazz_train.model
model.sh b_kar_train.arff b_kar_train.model
model.sh m_class_train.arff m_class_train.model
model.sh m_jazz_train.arff m_jazz_train.model
model.sh m_kar_train.arff m_kar_train.model
model.sh resample_a_class_train.arff resample_a_class_train.model
model.sh resample_a_jazz_train.arff resample_a_jazz_train.model
model.sh resample_a_kar_train.arff resample_a_kar_train.model
model.sh resample_b_class_train.arff resample_b_class_train.model
model.sh resample_b_jazz_train.arff resample_b_jazz_train.model
model.sh resample_b_kar_train.arff resample_b_kar_train.model
model.sh resample_m_class_train.arff resample_m_class_train.model
model.sh resample_m_jazz_train.arff resample_m_jazz_train.model
model.sh resample_m_kar_train.arff resample_m_kar_train.model
model.sh smote_a_class_train.arff smote_a_class_train.model
model.sh smote_a_jazz_train.arff smote_a_jazz_train.model
model.sh smote_a_kar_train.arff smote_a_kar_train.model
model.sh smote_b_class_train.arff smote_b_class_train.model
model.sh smote_b_jazz_train.arff smote_b_jazz_train.model
model.sh smote_b_kar_train.arff smote_b_kar_train.model
model.sh smote_m_class_train.arff smote_m_class_train.model
model.sh smote_m_jazz_train.arff smote_m_jazz_train.model
model.sh smote_m_kar_train.arff smote_m_kar_train.model
model.sh sss_a_class_train.arff sss_a_class_train.model
model.sh sss_a_jazz_train.arff sss_a_jazz_train.model
model.sh sss_a_kar_train.arff sss_a_kar_train.model
model.sh sss_b_class_train.arff sss_b_class_train.model
model.sh sss_b_jazz_train.arff sss_b_jazz_train.model
model.sh sss_b_kar_train.arff sss_b_kar_train.model
model.sh sss_m_class_train.arff sss_m_class_train.model
model.sh sss_m_jazz_train.arff sss_m_jazz_train.model
model.sh sss_m_kar_train.arff sss_m_kar_train.model
